version: "3"

services:
  manictime:
    image: manictime/manictimeserver:latest

    volumes:
      - "manictime-data:/app/Data"
      - "manictime-keys:/root/.aspnet/DataProtection-Keys"
      - "../manictime/ManicTimeServerSettings.json:/app/ManicTimeServerSettings.json"

    ports:
    #entrypoint: "bash" #./ManicTimeServer  addadmin -u user@example.com -p password" # Use this to add the first admin user

volumes:
  manictime-data:
  manictime-keys:
