version: "3"

services:

  tunnel:
    image: "cloudflare/cloudflared:2022.7.1"
    command: ["tunnel", "--no-autoupdate", "run", "--token", "${CF_TOKEN}"]

  nginx:
    image: nginx
    volumes:
      - "nginx-logs:/var/log/nginx"
      - "./nginx-templates:/etc/nginx/templates"
    environment:
      NGINX_PORT: 80
      DOWNSTREAM_PORT: "${APP_PORT:-8080}"
      DOWNSTREAM_HOST: "${APP_HOST:-app}"
      FQDN: "${APP_FQDN}"

  fail2ban:
    image: crazymax/fail2ban
    restart: unless-stopped
    volumes:
      - "./fail2ban-config:/data"
      - "fail2ban-db:/data/db"
      - "./nginx-action.local:/data/action.d/nginx-action.local"
      - "nginx-logs:/var/log/nginx:ro"

volumes:
  nginx-logs:
  fail2ban-db:
